apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  gateways:
    components:
      egressGateway:
        enabled: false
      ingressGateway:
        enabled: true
        k8s:
          overlays:
            - kind: Deployment
              name: istio-ingressgateway
              patches:
                - path: spec.template.spec.containers.[name:istio-proxy].ports.[containerPort:80].hostPort
                  value: 80
                - path: spec.template.spec.containers.[name:istio-proxy].ports.[containerPort:443].hostPort
                  value: 443