---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: all-users--graphql-manage-all
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  subjects:
  - user: "*"
    properties:
      request.auth.claims[email]: nobody@kyma.cx
  roleRef:
    kind: ServiceRole
    name: "graphql-manage-all"
