apiVersion: v1
kind: Service
metadata:
  name: istio-sample
  labels:
    app:  istio-sampler
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: istio-sampler
    release: {{ .Release.Name }}
